import type { Metadata } from "next";
import "../globals.css";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className="px-16 max-[1017px]:px-5">{children}</div>
      <Footer />
    </>
  );
}
